* orgabilize.el
Orgabilize (org + readable + -ize) is an Org-centric web page archiver for Emacs.
It caches web pages, helps you insert a link with a title, and converts web pages to Org files in an archive directory.
It uses [[https://gitlab.com/gardenappl/readability-cli][readability-cli]] to preprocess HTML.
It is an alternative to [[https://github.com/alphapapa/org-web-tools][org-web-tools]] which uses pandoc, but =orgabilize= focuses on producing highly readable Org output from modern web pages.
** Installation
Install [[https://gitlab.com/gardenappl/readability-cli][readability-cli]].
** Configuration
** Usage
:PROPERTIES:
:CREATED_TIME: [2021-04-11 Sun 13:14]
:END:
*** Inserting a link
Use =orgabilize-insert-org-link= to insert a link into an Org buffer with its title.
*** Inserting a table of contents
Use =orgabilize-insert-org-toc= to insert the table of contents of a document into an Org buffer.
*** Archiving to a directory
Run =orgabilize-org-archive= to convert a web page to Org and save it to a file in =orgabilize-org-archive-directory=.
