name: Build and test

on:
  push:
    paths:
      - '**.el'
  workflow_dispatch:



jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          accept-flake-config = true
    - name: Lint
      run: nix run .#nomake -- orgabilize
    - name: Test
      run: nix run .#test
