name: Build and test

on:
  push:
    paths:
      - '**.el'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          extra-substituters = https://emacs-ci.cachix.org
          extra-trusted-public-keys = emacs-ci.cachix.org-1:B5FVOrxhXXrOL0S+tQ7USrhjMT5iOPH+QN9q0NItom4=
    - name: Lint
      run: nix run .#nomake -- orgabilize
    - name: Test
      run: nix run .#test
